"""Shared domain primitives."""

from __future__ import annotations

from datetime import UTC, datetime
from enum import Enum  # noqa: UP042 — keep str,Enum for explicit value typing

import ulid


def utcnow() -> datetime:
    return datetime.now(UTC)


def as_utc(dt: datetime) -> datetime:
    """Normalize DB-returned datetimes (SQLite may drop tzinfo)."""
    if dt.tzinfo is None:
        return dt.replace(tzinfo=UTC)
    return dt.astimezone(UTC)


def new_id(prefix: str) -> str:
    """Opaque prefixed ULID identifier, e.g. PHX-PAT-01J..."""
    return f"{prefix}-{ulid.new()}"


class DataResidency(str, Enum):
    TR = "TR"
    EU = "EU"
    US = "US"
    OTHER = "OTHER"


class DataZone(str, Enum):
    RAW_CLINICAL = "RAW_CLINICAL"
    PROCESSED_CLINICAL = "PROCESSED_CLINICAL"
    CURATED = "CURATED"
    ML_APPROVED = "ML_APPROVED"


class AssetType(str, Enum):
    FASTQ_R1 = "FASTQ_R1"
    FASTQ_R2 = "FASTQ_R2"
    BAM = "BAM"
    CRAM = "CRAM"
    BAI = "BAI"
    CRAI = "CRAI"
    VCF = "VCF"
    GVCF = "GVCF"
    VCF_INDEX = "VCF_INDEX"
    QC = "QC"
    REPORT = "REPORT"
    OTHER = "OTHER"


class AssetStatus(str, Enum):
    UPLOAD_PENDING = "UPLOAD_PENDING"
    AVAILABLE = "AVAILABLE"
    PENDING_DELETION = "PENDING_DELETION"
    DELETED = "DELETED"


class AssetRelationKind(str, Enum):
    ORIGINAL = "ORIGINAL"
    SANITIZED = "SANITIZED"
    DERIVED = "DERIVED"


class ProcessingPurpose(str, Enum):
    CLINICAL_DIAGNOSIS = "CLINICAL_DIAGNOSIS"
    REANALYSIS = "REANALYSIS"
    QUALITY_CONTROL = "QUALITY_CONTROL"
    VALIDATION = "VALIDATION"
    RESEARCH = "RESEARCH"
    ML_TRAINING = "ML_TRAINING"
    ML_EXTERNAL_VALIDATION = "ML_EXTERNAL_VALIDATION"


class CurationStatus(str, Enum):
    RAW = "RAW"
    TECHNICALLY_VALID = "TECHNICALLY_VALID"
    INTERPRETATION_UNKNOWN = "INTERPRETATION_UNKNOWN"
    PARTIALLY_CURATED = "PARTIALLY_CURATED"
    EXPERT_REVIEWED = "EXPERT_REVIEWED"
    GOLD_STANDARD = "GOLD_STANDARD"


class MlEligibilityStatus(str, Enum):
    NOT_EVALUATED = "NOT_EVALUATED"
    INELIGIBLE = "INELIGIBLE"
    PENDING_REVIEW = "PENDING_REVIEW"
    APPROVED = "APPROVED"
    REVOKED = "REVOKED"


class DatasetRole(str, Enum):
    TRAINING = "TRAINING"
    VALIDATION = "VALIDATION"
    TEST = "TEST"
    EXTERNAL_VALIDATION = "EXTERNAL_VALIDATION"
    BENCHMARK = "BENCHMARK"
    NONE = "NONE"


class DatasetSource(str, Enum):
    INTERNAL = "INTERNAL"
    CLINGEN = "CLINGEN"
    CLINVAR = "CLINVAR"
    GIAB = "GIAB"
    PUBLIC_RESEARCH = "PUBLIC_RESEARCH"
    EXTERNAL_PARTNER = "EXTERNAL_PARTNER"
    OTHER = "OTHER"


class DatasetApprovalState(str, Enum):
    DRAFT = "DRAFT"
    PENDING_APPROVAL = "PENDING_APPROVAL"
    APPROVED = "APPROVED"
    REVOKED = "REVOKED"


class RetentionAction(str, Enum):
    REVIEW = "REVIEW"
    ARCHIVE = "ARCHIVE"
    DELETE = "DELETE"


class Role(str, Enum):
    SYSTEM_ADMIN = "SYSTEM_ADMIN"
    TENANT_ADMIN = "TENANT_ADMIN"
    CLINICAL_GENETICIST = "CLINICAL_GENETICIST"
    BIOINFORMATICIAN = "BIOINFORMATICIAN"
    LAB_TECHNICIAN = "LAB_TECHNICIAN"
    DATA_CURATOR = "DATA_CURATOR"
    ML_RESEARCHER = "ML_RESEARCHER"
    AUDITOR = "AUDITOR"


class Permission(str, Enum):
    TENANT_MANAGE = "TENANT_MANAGE"
    PATIENT_CREATE = "PATIENT_CREATE"
    PATIENT_READ = "PATIENT_READ"
    IDENTITY_MAPPING_READ = "IDENTITY_MAPPING_READ"
    IDENTITY_MAPPING_WRITE = "IDENTITY_MAPPING_WRITE"
    SAMPLE_MANAGE = "SAMPLE_MANAGE"
    ASSET_UPLOAD = "ASSET_UPLOAD"
    ASSET_READ_META = "ASSET_READ_META"
    ASSET_DOWNLOAD = "ASSET_DOWNLOAD"
    ASSET_DELETE = "ASSET_DELETE"
    CASE_CURATE = "CASE_CURATE"
    ML_ELIGIBILITY_MANAGE = "ML_ELIGIBILITY_MANAGE"
    DATASET_MANAGE = "DATASET_MANAGE"
    DATASET_APPROVE = "DATASET_APPROVE"
    DATASET_EXPORT = "DATASET_EXPORT"
    GOVERNANCE_MANAGE = "GOVERNANCE_MANAGE"
    RETENTION_MANAGE = "RETENTION_MANAGE"
    AUDIT_READ = "AUDIT_READ"


class AuditAction(str, Enum):
    LOGIN = "LOGIN"
    LOGIN_FAILED = "LOGIN_FAILED"
    ASSET_CREATED = "ASSET_CREATED"
    ASSET_UPLOADED = "ASSET_UPLOADED"
    ASSET_DOWNLOADED = "ASSET_DOWNLOADED"
    ASSET_DELETED = "ASSET_DELETED"
    PATIENT_CREATED = "PATIENT_CREATED"
    PATIENT_UPDATED = "PATIENT_UPDATED"
    IDENTITY_MAPPING_ACCESSED = "IDENTITY_MAPPING_ACCESSED"
    DATASET_CREATED = "DATASET_CREATED"
    DATASET_APPROVED = "DATASET_APPROVED"
    DATASET_EXPORTED = "DATASET_EXPORTED"
    ML_ELIGIBILITY_CHANGED = "ML_ELIGIBILITY_CHANGED"
    CURATION_STATUS_CHANGED = "CURATION_STATUS_CHANGED"
    RETENTION_POLICY_CHANGED = "RETENTION_POLICY_CHANGED"
    ACCESS_DENIED = "ACCESS_DENIED"
    TENANT_CREATED = "TENANT_CREATED"
    SAMPLE_CREATED = "SAMPLE_CREATED"
    CASE_CREATED = "CASE_CREATED"
    UPLOAD_SESSION_CREATED = "UPLOAD_SESSION_CREATED"
